### ISSUE TITLE
Create Keptn Shipyard file for Flux Demo

### ISSUE THREAD

**Issue by bradmccoydev** [keptn-sandbox/keptn-flux-integration#22]
For our Keptn Flux Integration, we will need to create a shipyard file to use so that we can use to send the event to.

Reach out to Adam Gardner for his Hello world example, he also has a blog on this.

https://agardner.net/keptn-hello-world/

Acceptance Criteria:
Get this working on your local computer and showcase it working

**Comment by mehabhalodiya** [comment]
@bradmccoydev can we take a help of this: [keptn.sh/docs/0.15.x/manage/shipyard/](https://keptn.sh/docs/0.15.x/manage/shipyard/)?

**Comment by bradmccoydev** [comment]
yes you can use that to help you, just do a hello world one and get it working on your computer doing the tutorials will help

**Comment by mehabhalodiya** [comment]
@bradmccoydev  created a `shipyard.yaml`:
```
apiVersion: spec.keptn.sh/0.2.3
kind: "Shipyard"
metadata:
  name: "flux"
spec:
  stages:
    - name: "test"
      sequences:
      - name: "delivery"
        tasks: 
        - name: "test"
        - name: "promote"
    - name: "uat"
      sequences:
      - name: "delivery"
        triggeredOn:
          - event: "test.delivery.finished"
        tasks: 
        - name: "test"
        - name: "promote"
    - name: "prod"
      sequences:
      - name: "delivery"
        triggeredOn:
          - event: "uat.delivery.finished"
            selector:
              match:
              result: "pass"
        tasks: 
        - name: "test"
```
And I got it working in the Keptn Bridge:

![Keptn_bridge_jes](https://user-images.githubusercontent.com/73488906/177320861-474854c6-3d46-481b-b5ac-3a2fa9c20b1f.png)
